// const myKey = config.API;

// function initMap() {
//   const sneakyCleanHouston = { lat: 29.795, lng: -95.569 };
//   const houstonMap = new google.maps.Map(
//     document.getElementById("houston-map"),
//     {
//       zoom: 12,
//       center: sneakyCleanHouston,
//     }
//   );
//   const houstonMarker = new google.maps.Marker({
//     position: sneakyCleanHouston,
//     map: houstonMap,
//   });
//   const sneakyCleanAtlanta = { lat: 33.848, lng: -84.373 };
//   const atlantaMap = new google.maps.Map(
//     document.getElementById("atlanta-map"),
//     {
//       zoom: 12,
//       center: sneakyCleanAtlanta,
//     }
//   );
//   const atlantaMarker = new google.maps.Marker({
//     position: sneakyCleanAtlanta,
//     map: atlantaMap,
//   });
//   const sneakyCleanTampa = { lat: 27.947, lng: -82.452 };
//   const tampaMap = new google.maps.Map(document.getElementById("tampa-map"), {
//     zoom: 12,
//     center: sneakyCleanTampa,
//   });
//   const tampaMarker = new google.maps.Marker({
//     position: sneakyCleanTampa,
//     map: tampaMap,
//   });
// }

const zipsWithin50MilesHouston = [
  {
    zip_code: "77516",
    distance: 46.057,
    city: "Angleton",
    state: "TX",
  },
  {
    zip_code: "77486",
    distance: 45.403,
    city: "West Columbia",
    state: "TX",
  },
  {
    zip_code: "77515",
    distance: 44.686,
    city: "Angleton",
    state: "TX",
  },
  {
    zip_code: "77431",
    distance: 43.665,
    city: "Danciger",
    state: "TX",
  },
  {
    zip_code: "77463",
    distance: 43.665,
    city: "Old Ocean",
    state: "TX",
  },
  {
    zip_code: "77453",
    distance: 48.215,
    city: "Lane City",
    state: "TX",
  },
  {
    zip_code: "77534",
    distance: 43.211,
    city: "Danbury",
    state: "TX",
  },
  {
    zip_code: "77420",
    distance: 43.424,
    city: "Boling",
    state: "TX",
  },
  {
    zip_code: "77430",
    distance: 38.402,
    city: "Damon",
    state: "TX",
  },
  {
    zip_code: "77577",
    distance: 40.68,
    city: "Liverpool",
    state: "TX",
  },
  {
    zip_code: "77444",
    distance: 38.055,
    city: "Guy",
    state: "TX",
  },
  {
    zip_code: "77563",
    distance: 48.276,
    city: "Hitchcock",
    state: "TX",
  },
  {
    zip_code: "77488",
    distance: 46.239,
    city: "Wharton",
    state: "TX",
  },
  {
    zip_code: "77443",
    distance: 48.452,
    city: "Glen Flora",
    state: "TX",
  },
  {
    zip_code: "77510",
    distance: 43.049,
    city: "Santa Fe",
    state: "TX",
  },
  {
    zip_code: "77568",
    distance: 47.71,
    city: "La Marque",
    state: "TX",
  },
  {
    zip_code: "77517",
    distance: 41.169,
    city: "Santa Fe",
    state: "TX",
  },
  {
    zip_code: "77511",
    distance: 36.168,
    city: "Alvin",
    state: "TX",
  },
  {
    zip_code: "77583",
    distance: 30.502,
    city: "Rosharon",
    state: "TX",
  },
  {
    zip_code: "77461",
    distance: 32.427,
    city: "Needville",
    state: "TX",
  },
  {
    zip_code: "77590",
    distance: 49.34,
    city: "Texas City",
    state: "TX",
  },
  {
    zip_code: "77591",
    distance: 45.332,
    city: "Texas City",
    state: "TX",
  },
  {
    zip_code: "77592",
    distance: 47.545,
    city: "Texas City",
    state: "TX",
  },
  {
    zip_code: "77448",
    distance: 40.592,
    city: "Hungerford",
    state: "TX",
  },
  {
    zip_code: "77436",
    distance: 47.697,
    city: "Egypt",
    state: "TX",
  },
  {
    zip_code: "77512",
    distance: 33.497,
    city: "Alvin",
    state: "TX",
  },
  {
    zip_code: "77451",
    distance: 36.204,
    city: "Kendleton",
    state: "TX",
  },
  {
    zip_code: "77539",
    distance: 41.629,
    city: "Dickinson",
    state: "TX",
  },
  {
    zip_code: "77417",
    distance: 33.142,
    city: "Beasley",
    state: "TX",
  },
  {
    zip_code: "77481",
    distance: 23.377,
    city: "Thompsons",
    state: "TX",
  },
  {
    zip_code: "77574",
    distance: 37.014,
    city: "League City",
    state: "TX",
  },
  {
    zip_code: "77578",
    distance: 26.368,
    city: "Manvel",
    state: "TX",
  },
  {
    zip_code: "77469",
    distance: 23.388,
    city: "Richmond",
    state: "TX",
  },
  {
    zip_code: "77573",
    distance: 36.634,
    city: "League City",
    state: "TX",
  },
  {
    zip_code: "77518",
    distance: 41.568,
    city: "Bacliff",
    state: "TX",
  },
  {
    zip_code: "77549",
    distance: 31.529,
    city: "Friendswood",
    state: "TX",
  },
  {
    zip_code: "77546",
    distance: 31.196,
    city: "Friendswood",
    state: "TX",
  },
  {
    zip_code: "77435",
    distance: 38.116,
    city: "East Bernard",
    state: "TX",
  },
  {
    zip_code: "77454",
    distance: 41.931,
    city: "Lissie",
    state: "TX",
  },
  {
    zip_code: "77434",
    distance: 47.453,
    city: "Eagle Lake",
    state: "TX",
  },
  {
    zip_code: "77459",
    distance: 19.822,
    city: "Missouri City",
    state: "TX",
  },
  {
    zip_code: "77565",
    distance: 38.545,
    city: "Kemah",
    state: "TX",
  },
  {
    zip_code: "77545",
    distance: 20.027,
    city: "Fresno",
    state: "TX",
  },
  {
    zip_code: "77598",
    distance: 32.878,
    city: "Webster",
    state: "TX",
  },
  {
    zip_code: "77584",
    distance: 23.139,
    city: "Pearland",
    state: "TX",
  },
  {
    zip_code: "77471",
    distance: 24.597,
    city: "Rosenberg",
    state: "TX",
  },
  {
    zip_code: "77588",
    distance: 26.106,
    city: "Pearland",
    state: "TX",
  },
  {
    zip_code: "77581",
    distance: 25.134,
    city: "Pearland",
    state: "TX",
  },
  {
    zip_code: "77058",
    distance: 33.843,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77479",
    distance: 17.132,
    city: "Sugar Land",
    state: "TX",
  },
  {
    zip_code: "77062",
    distance: 31.823,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77053",
    distance: 17.394,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77586",
    distance: 36.49,
    city: "Seabrook",
    state: "TX",
  },
  {
    zip_code: "77089",
    distance: 26.539,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77464",
    distance: 26.888,
    city: "Orchard",
    state: "TX",
  },
  {
    zip_code: "77489",
    distance: 15.124,
    city: "Missouri City",
    state: "TX",
  },
  {
    zip_code: "77487",
    distance: 13.966,
    city: "Sugar Land",
    state: "TX",
  },
  {
    zip_code: "77496",
    distance: 13.966,
    city: "Sugar Land",
    state: "TX",
  },
  {
    zip_code: "77047",
    distance: 18.25,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77059",
    distance: 31.07,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77048",
    distance: 20.521,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77034",
    distance: 27.041,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77497",
    distance: 13.273,
    city: "Stafford",
    state: "TX",
  },
  {
    zip_code: "77478",
    distance: 13.229,
    city: "Sugar Land",
    state: "TX",
  },
  {
    zip_code: "77075",
    distance: 23.068,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77085",
    distance: 14.455,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77477",
    distance: 12.936,
    city: "Stafford",
    state: "TX",
  },
  {
    zip_code: "77507",
    distance: 33.833,
    city: "Pasadena",
    state: "TX",
  },
  {
    zip_code: "77485",
    distance: 30.794,
    city: "Wallis",
    state: "TX",
  },
  {
    zip_code: "77045",
    distance: 15.148,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77246",
    distance: 15.02,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77247",
    distance: 15.02,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77498",
    distance: 12.266,
    city: "Sugar Land",
    state: "TX",
  },
  {
    zip_code: "77505",
    distance: 29.019,
    city: "Pasadena",
    state: "TX",
  },
  {
    zip_code: "77406",
    distance: 16.971,
    city: "Richmond",
    state: "TX",
  },
  {
    zip_code: "77061",
    distance: 21.687,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77504",
    distance: 26.227,
    city: "Pasadena",
    state: "TX",
  },
  {
    zip_code: "77071",
    distance: 11.667,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77031",
    distance: 11.205,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77035",
    distance: 12.715,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77051",
    distance: 16.357,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77501",
    distance: 28.097,
    city: "Pasadena",
    state: "TX",
  },
  {
    zip_code: "77508",
    distance: 28.097,
    city: "Pasadena",
    state: "TX",
  },
  {
    zip_code: "77572",
    distance: 34.313,
    city: "La Porte",
    state: "TX",
  },
  {
    zip_code: "77587",
    distance: 23.695,
    city: "South Houston",
    state: "TX",
  },
  {
    zip_code: "77033",
    distance: 17.99,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77407",
    distance: 12.225,
    city: "Richmond",
    state: "TX",
  },
  {
    zip_code: "77286",
    distance: 16.625,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77260",
    distance: 22.87,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77441",
    distance: 22.453,
    city: "Fulshear",
    state: "TX",
  },
  {
    zip_code: "77099",
    distance: 9.68,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77096",
    distance: 11.305,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77502",
    distance: 24.819,
    city: "Pasadena",
    state: "TX",
  },
  {
    zip_code: "77054",
    distance: 14.072,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77025",
    distance: 12.489,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77087",
    distance: 18.908,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77476",
    distance: 23.623,
    city: "Simonton",
    state: "TX",
  },
  {
    zip_code: "77074",
    distance: 9.462,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77571",
    distance: 32.767,
    city: "La Porte",
    state: "TX",
  },
  {
    zip_code: "77017",
    distance: 21.62,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77083",
    distance: 8.94,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77021",
    distance: 15.734,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77536",
    distance: 28.87,
    city: "Deer Park",
    state: "TX",
  },
  {
    zip_code: "77072",
    distance: 7.688,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77411",
    distance: 7.669,
    city: "Alief",
    state: "TX",
  },
  {
    zip_code: "77250",
    distance: 8.344,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77402",
    distance: 10.718,
    city: "Bellaire",
    state: "TX",
  },
  {
    zip_code: "77036",
    distance: 8.122,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77503",
    distance: 26.593,
    city: "Pasadena",
    state: "TX",
  },
  {
    zip_code: "77401",
    distance: 10.473,
    city: "Bellaire",
    state: "TX",
  },
  {
    zip_code: "77030",
    distance: 13.143,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77081",
    distance: 9.237,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77506",
    distance: 24.046,
    city: "Pasadena",
    state: "TX",
  },
  {
    zip_code: "77005",
    distance: 11.579,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77012",
    distance: 19.69,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77023",
    distance: 17.124,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77082",
    distance: 6.824,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77004",
    distance: 14.536,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77520",
    distance: 35.831,
    city: "Baytown",
    state: "TX",
  },
  {
    zip_code: "77046",
    distance: 10.523,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77098",
    distance: 11.39,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77547",
    distance: 21.426,
    city: "Galena Park",
    state: "TX",
  },
  {
    zip_code: "77063",
    distance: 6.335,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77522",
    distance: 37.807,
    city: "Baytown",
    state: "TX",
  },
  {
    zip_code: "77027",
    distance: 9.65,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77494",
    distance: 15.484,
    city: "Katy",
    state: "TX",
  },
  {
    zip_code: "77006",
    distance: 12.58,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77042",
    distance: 5.032,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77011",
    distance: 17.177,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77057",
    distance: 7.421,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77450",
    distance: 10.451,
    city: "Katy",
    state: "TX",
  },
  {
    zip_code: "77056",
    distance: 8.183,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77003",
    distance: 14.937,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77276",
    distance: 14.112,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77285",
    distance: 14.112,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77077",
    distance: 4.571,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77010",
    distance: 14.071,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77019",
    distance: 11.222,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77002",
    distance: 13.679,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77029",
    distance: 20.003,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77278",
    distance: 5.713,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77001",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77052",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77202",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77203",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77204",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77205",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77206",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77207",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77208",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77209",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77210",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77212",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77213",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77215",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77216",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77217",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77218",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77219",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77220",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77221",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77222",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77223",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77224",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77225",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77226",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77227",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77228",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77229",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77230",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77231",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77233",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77234",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77235",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77236",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77237",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77238",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77240",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77241",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77242",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77243",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77244",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77245",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77248",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77249",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77251",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77252",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77253",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77254",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77255",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77256",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77257",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77258",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77259",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77261",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77262",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77263",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77265",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77266",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77267",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77268",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77269",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77270",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77271",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77272",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77273",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77274",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77275",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77277",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77279",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77280",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77282",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77284",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77287",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77288",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77289",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77290",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77291",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77292",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77293",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77297",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77299",
    distance: 12.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77097",
    distance: 13.92,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77296",
    distance: 13.92,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77298",
    distance: 13.92,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77015",
    distance: 24.915,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77201",
    distance: 13.587,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77094",
    distance: 6.45,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77007",
    distance: 10.76,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77024",
    distance: 5.002,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77020",
    distance: 16.424,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77079",
    distance: 2.646,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77474",
    distance: 35.826,
    city: "Sealy",
    state: "TX",
  },
  {
    zip_code: "77530",
    distance: 28.086,
    city: "Channelview",
    state: "TX",
  },
  {
    zip_code: "77523",
    distance: 43.55,
    city: "Baytown",
    state: "TX",
  },
  {
    zip_code: "77491",
    distance: 14.158,
    city: "Katy",
    state: "TX",
  },
  {
    zip_code: "77492",
    distance: 14.158,
    city: "Katy",
    state: "TX",
  },
  {
    zip_code: "78933",
    distance: 46.431,
    city: "Cat Spring",
    state: "TX",
  },
  {
    zip_code: "77466",
    distance: 25.658,
    city: "Pattison",
    state: "TX",
  },
  {
    zip_code: "77473",
    distance: 31.382,
    city: "San Felipe",
    state: "TX",
  },
  {
    zip_code: "77013",
    distance: 21.051,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77009",
    distance: 13.064,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77055",
    distance: 5.683,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77008",
    distance: 10.103,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77026",
    distance: 15.373,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77521",
    distance: 36.863,
    city: "Baytown",
    state: "TX",
  },
  {
    zip_code: "77043",
    distance: 0,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77080",
    distance: 3.726,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77018",
    distance: 9.574,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77084",
    distance: 4.642,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77028",
    distance: 17.864,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77413",
    distance: 11.172,
    city: "Barker",
    state: "TX",
  },
  {
    zip_code: "77092",
    distance: 6.759,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77022",
    distance: 12.378,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77049",
    distance: 26.181,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77562",
    distance: 32.015,
    city: "Highlands",
    state: "TX",
  },
  {
    zip_code: "77449",
    distance: 9.117,
    city: "Katy",
    state: "TX",
  },
  {
    zip_code: "77078",
    distance: 20.021,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77091",
    distance: 9.391,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77493",
    distance: 15.053,
    city: "Katy",
    state: "TX",
  },
  {
    zip_code: "77423",
    distance: 23.736,
    city: "Brookshire",
    state: "TX",
  },
  {
    zip_code: "77041",
    distance: 3.302,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77294",
    distance: 20.949,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77076",
    distance: 12.621,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77016",
    distance: 17.436,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77093",
    distance: 15.038,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77580",
    distance: 43.827,
    city: "Mont Belvieu",
    state: "TX",
  },
  {
    zip_code: "77040",
    distance: 5.601,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77088",
    distance: 9.309,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77037",
    distance: 12.775,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77050",
    distance: 19.956,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77044",
    distance: 25.124,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77095",
    distance: 7.892,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77039",
    distance: 16.151,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77064",
    distance: 7.966,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77038",
    distance: 11.383,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77086",
    distance: 9.333,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77065",
    distance: 8.065,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77532",
    distance: 32.719,
    city: "Crosby",
    state: "TX",
  },
  {
    zip_code: "77433",
    distance: 12.947,
    city: "Cypress",
    state: "TX",
  },
  {
    zip_code: "77060",
    distance: 14.145,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77396",
    distance: 21.56,
    city: "Humble",
    state: "TX",
  },
  {
    zip_code: "77315",
    distance: 17.525,
    city: "North Houston",
    state: "TX",
  },
  {
    zip_code: "77067",
    distance: 12.817,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77066",
    distance: 11.221,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77410",
    distance: 12.083,
    city: "Cypress",
    state: "TX",
  },
  {
    zip_code: "77070",
    distance: 11.681,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77014",
    distance: 13.815,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77418",
    distance: 41.826,
    city: "Bellville",
    state: "TX",
  },
  {
    zip_code: "77032",
    distance: 18.482,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77069",
    distance: 12.681,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77325",
    distance: 23.058,
    city: "Kingwood",
    state: "TX",
  },
  {
    zip_code: "77347",
    distance: 23.058,
    city: "Humble",
    state: "TX",
  },
  {
    zip_code: "77346",
    distance: 27.499,
    city: "Humble",
    state: "TX",
  },
  {
    zip_code: "77429",
    distance: 13.864,
    city: "Cypress",
    state: "TX",
  },
  {
    zip_code: "77073",
    distance: 17.065,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77068",
    distance: 14.726,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77090",
    distance: 16.2,
    city: "Houston",
    state: "TX",
  },
  {
    zip_code: "77338",
    distance: 22.868,
    city: "Humble",
    state: "TX",
  },
  {
    zip_code: "77452",
    distance: 45.103,
    city: "Kenney",
    state: "TX",
  },
  {
    zip_code: "77379",
    distance: 16.238,
    city: "Spring",
    state: "TX",
  },
  {
    zip_code: "77339",
    distance: 27.205,
    city: "Kingwood",
    state: "TX",
  },
  {
    zip_code: "77447",
    distance: 22.117,
    city: "Hockley",
    state: "TX",
  },
  {
    zip_code: "77345",
    distance: 30.549,
    city: "Kingwood",
    state: "TX",
  },
  {
    zip_code: "77535",
    distance: 43.113,
    city: "Dayton",
    state: "TX",
  },
  {
    zip_code: "77388",
    distance: 18.374,
    city: "Spring",
    state: "TX",
  },
  {
    zip_code: "77383",
    distance: 21.122,
    city: "Spring",
    state: "TX",
  },
  {
    zip_code: "77387",
    distance: 21.122,
    city: "Spring",
    state: "TX",
  },
  {
    zip_code: "77391",
    distance: 21.122,
    city: "Spring",
    state: "TX",
  },
  {
    zip_code: "77393",
    distance: 21.122,
    city: "Spring",
    state: "TX",
  },
  {
    zip_code: "77377",
    distance: 18.272,
    city: "Tomball",
    state: "TX",
  },
  {
    zip_code: "77373",
    distance: 21.127,
    city: "Spring",
    state: "TX",
  },
  {
    zip_code: "77336",
    distance: 33.911,
    city: "Huffman",
    state: "TX",
  },
  {
    zip_code: "77484",
    distance: 27.861,
    city: "Waller",
    state: "TX",
  },
  {
    zip_code: "77446",
    distance: 30.872,
    city: "Prairie View",
    state: "TX",
  },
  {
    zip_code: "77375",
    distance: 19.62,
    city: "Tomball",
    state: "TX",
  },
  {
    zip_code: "77386",
    distance: 24.227,
    city: "Spring",
    state: "TX",
  },
  {
    zip_code: "77445",
    distance: 34.792,
    city: "Hempstead",
    state: "TX",
  },
  {
    zip_code: "77365",
    distance: 26.724,
    city: "Porter",
    state: "TX",
  },
  {
    zip_code: "77337",
    distance: 21.356,
    city: "Hufsmith",
    state: "TX",
  },
  {
    zip_code: "77426",
    distance: 45.71,
    city: "Chappell Hill",
    state: "TX",
  },
  {
    zip_code: "77389",
    distance: 21.971,
    city: "Spring",
    state: "TX",
  },
  {
    zip_code: "77380",
    distance: 23.576,
    city: "Spring",
    state: "TX",
  },
  {
    zip_code: "77355",
    distance: 25.809,
    city: "Magnolia",
    state: "TX",
  },
  {
    zip_code: "77362",
    distance: 24.676,
    city: "Pinehurst",
    state: "TX",
  },
  {
    zip_code: "77357",
    distance: 33.814,
    city: "New Caney",
    state: "TX",
  },
  {
    zip_code: "77381",
    distance: 25.868,
    city: "Spring",
    state: "TX",
  },
  {
    zip_code: "77385",
    distance: 27.95,
    city: "Conroe",
    state: "TX",
  },
  {
    zip_code: "77382",
    distance: 26.629,
    city: "Spring",
    state: "TX",
  },
  {
    zip_code: "77353",
    distance: 29.096,
    city: "Magnolia",
    state: "TX",
  },
  {
    zip_code: "77354",
    distance: 28.295,
    city: "Magnolia",
    state: "TX",
  },
  {
    zip_code: "77302",
    distance: 31.988,
    city: "Conroe",
    state: "TX",
  },
  {
    zip_code: "77384",
    distance: 29.698,
    city: "Conroe",
    state: "TX",
  },
  {
    zip_code: "77372",
    distance: 39.098,
    city: "Splendora",
    state: "TX",
  },
  {
    zip_code: "77306",
    distance: 36.629,
    city: "Conroe",
    state: "TX",
  },
  {
    zip_code: "77880",
    distance: 48.874,
    city: "Washington",
    state: "TX",
  },
  {
    zip_code: "77316",
    distance: 34.749,
    city: "Montgomery",
    state: "TX",
  },
  {
    zip_code: "77301",
    distance: 35.636,
    city: "Conroe",
    state: "TX",
  },
  {
    zip_code: "77363",
    distance: 38.358,
    city: "Plantersville",
    state: "TX",
  },
  {
    zip_code: "77305",
    distance: 35.835,
    city: "Conroe",
    state: "TX",
  },
  {
    zip_code: "77304",
    distance: 35.944,
    city: "Conroe",
    state: "TX",
  },
  {
    zip_code: "77869",
    distance: 46.836,
    city: "Navasota",
    state: "TX",
  },
  {
    zip_code: "77868",
    distance: 47.243,
    city: "Navasota",
    state: "TX",
  },
  {
    zip_code: "77303",
    distance: 41.091,
    city: "Conroe",
    state: "TX",
  },
  {
    zip_code: "77333",
    distance: 40.413,
    city: "Dobbin",
    state: "TX",
  },
  {
    zip_code: "77328",
    distance: 46.556,
    city: "Cleveland",
    state: "TX",
  },
  {
    zip_code: "77318",
    distance: 43.489,
    city: "Willis",
    state: "TX",
  },
  {
    zip_code: "77356",
    distance: 46.058,
    city: "Montgomery",
    state: "TX",
  },
  {
    zip_code: "77378",
    distance: 47.507,
    city: "Willis",
    state: "TX",
  },
];

// var __FOUND = zipsWithin50MilesHouston.find(function (post, index) {
//   if (post.zip_code === "77378") {
//     return true;
//   } else {
//     return false;
//   }
// });

// console.log(__FOUND);

const zipInputBox = document.querySelector(".zip-code");
const zipSearchButton = document.querySelector(".zip-search-button");
const zipResponse = document.querySelector(".zip-query-answer");

const checkZip = () => {
  const searchCriteria = zipInputBox.value;
  const zipSearch = zipsWithin50MilesHouston.find(function (post, index) {
    if (post.zip_code === searchCriteria) {
      zipResponse.innerHTML = "We service your area!";
    } else {
      zipResponse.innerHTML = "We don't service your area!";
    }
  });
};

zipSearchButton.addEventListener("click", (e) => {
  checkZip();
});
